# Generated by Django 4.1.2 on 2022-10-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='method',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start',
        ),
    ]
