# Generated by Django 4.1.2 on 2022-10-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_course_method_remove_course_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
