# Generated by Django 4.1.2 on 2022-10-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
