# Generated by Django 4.1.2 on 2022-10-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_staff_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
